language: swift
osx_image: xcode11
sudo: required
install:
  - wget https://swift.org/builds/swift-5.1-release/xcode/swift-5.1-RELEASE/swift-5.1-RELEASE-osx-symbols.pkg
  - sudo installer -pkg swift-5.1-RELEASE-osx-symbols.pkg -target /
  - export PATH="/Library/Developer/Toolchains/$SWIFT_VERSION.xctoolchain/usr/bin:$PATH"
script:
  - swift package update
  - swift test --enable-code-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
